### PR TITLE
Mark the NVIDIA compiler as supported

### PR DESCRIPTION
**Pull request by mclow**
See https://svn.boost.org/trac10/ticket/13447

### CODE REVIEW

**Comment by Flast** [comment]
Newly added condition always unused because line 74 contains `defined __CUDACC__`, and then `BOOST_PP_VARIADICS` will be 0.

**Comment by eldiener** [comment]
Is __CUDACC__ ever defined when compiling with another compiler than NVidia ? I pushed a change to develop which should fix this problem assuming that __CUDACC__ was only defined by NVidia, and not by anyone else. Also the change assumes that all versions of the NVidia compiler supports variadic macros.

**Comment by Flast** [comment]
AFAIK no compiler except nvcc define the symbol; I said `define"d" __CUDACC__` not `define __CUDACC__`. @eldiener your change is right.

**Comment by eldiener** [comment]
OK, I intend to close this PR.

**Comment by mclow** [comment]
Fine w/me.

**Comment by theZiz** [comment]
Thanks a lot!

**Pull request closed without merging**
