### PR TITLE
GitHub Actions config

### PR DESCRIPTION
**Pull request by sdarwin**
GitHub Actions CI script, generated from the .travis.yml file. Please refer to https://github.com/CPPAlliance/githubactions for more information and instructions.

### CODE REVIEW

**Comment by eldiener** [comment]
Why would I need this when I already have a travis.yml, an appveyor.yml, and your own drone.star ? Please explain what is accomplished by all this CI testing stuff. I readily admit that I find all this testing stuff confusing and a PITA in trying to understand how all this works or works together.

**Comment by sdarwin** [comment]
@eldiener , answered in the Issue: https://github.com/CPPAlliance/githubactions/issues/1

It is true that the tests are to a great degree redundant.   As long as travis, appveyor, and drone are all working, GitHub Actions may be overkill.   

But it can't hurt to have two systems running the same test, in case there's a failure, you can compare the results.

**Comment by eldiener** [comment]
I really do not want to have CI running the same set of tests redundantly within different CI testing contexts. I am perfectly willing to defer to you or others as far as what is the most effective CI setup for this library, but I see no benefit of redundancy every time some change is made to the library.

**Comment by Flamefire** [comment]
@pdimov added a [CI config for GHA](https://github.com/boostorg/preprocessor/blob/develop/.github/workflows/ci.yml) so this can be closed

**Pull request closed without merging**
